try: 
    my_dict = {"a": 1, "b": 2, "c": 3}     print(my_dict["d"]) except KeyError as e: 
    print("KeyError occurred:", e) finally: 
    print("This will always execute regardless of whether an exception occurred or not.") 
